name: linters

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    
   

    - name: Install packages
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo 'export PATH="$HOME/.local/bin:$PATH"' >> .bashrc
        python --version
        poetry --version
        poetry install

      name: Black test 
      run: poetry run black src

    - name: Flake8 test
      run: poetry run flake8 src

    - name: MyPy test
      run: poetry run mypy src


    
